title: deep-forest
repo: https://github.com/ian-pvd/deep-forest
author:
  name: ian-pvd
  email: pvdindustrial@gmail.com

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings

description: >
  my jekyll portfolio description

# To enable Google Analytics, add your tracking ID here.
# google_analytics: UA-NNNNNNNN-N

# Add pages to the navigation in this order.
header_pages:
  - about.md

theme_color: light # possible values: light dark
reduce_motion: true # possible values: true false

# Social media links
social_links:
 - { platform: github,         user_url: "https://github.com/ian-pvd/deep-forest" }


# Build settings

# SCSS config
sass:
  sass_dir: _sass
  style: nested # possible values: nested expanded compact compressed
